# Generated by Django 4.0.2 on 2022-02-22 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('url', models.TextField()),
                ('brief', models.TextField(null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.subject')),
            ],
        ),
    ]
