# Generated by Django 4.0.2 on 2022-02-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='content',
            name='brief',
            field=models.TextField(default=''),
        ),
    ]
