# Generated by Django 4.0.2 on 2022-02-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_data_content_date_alter_content_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='brief',
            field=models.TextField(blank=True, null=True),
        ),
    ]
