# Generated by Django 4.0.2 on 2022-02-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_content_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='webhook_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
